### ISSUE TITLE
Is the example for ios

### ISSUE THREAD

**Issue by joeyhipolito** [firebase/firebase-login-demo-phonegap#5]
I've tried using and building this, tested with an emulator and this gives me a white screen after login, probably some because the cordova.js file is for ios platform? where are the ones for android?

**Comment by siddhartham** [comment]
Any update on this yet ?

**Comment by Ghostavio** [comment]
I'm having an issue with URL not allowed, just cloned the repo and tried to run in an emulator:
![screen shot 2015-01-03 at 17 37 39](https://cloud.githubusercontent.com/assets/377506/5602560/65a88a42-936f-11e4-9533-4536440b6fc0.png)

**Comment by robertdimarco** [comment]
@siddhartham What is your question referring to?

@Ghostavio You'll need to create a new Facebook application and configure it (in Facebook's dashboard) and in Firebase (set the Facebook app id / secrets) to use this library and login flow.

**Comment by Ghostavio** [comment]
@robertdimarco I did that, same thing :/

**Comment by robertdimarco** [comment]
@Ghostavio You'll have to give me a bit more to go off of... Share the URL you have configured for your callback URL in Facebook, and any other non-standard app settings? You can ping me at the email addr above.

**Comment by Ghostavio** [comment]
what URL should I use for the callback? I'm using this for now: `https://auth.firebase.com/auth/facebook/callback`

**Comment by robertdimarco** [comment]
@Ghostavio Per [https://www.firebase.com/docs/web/guide/login/facebook.html](https://www.firebase.com/docs/web/guide/login/facebook.html), the callback URL should be set to `https://auth.firebase.com/v2/<YOUR-FIREBASE>/auth/facebook/callback`.

**Comment by robertdimarco** [comment]
FYI - I am closing this thread. If you believe you have found a bug, please file a new issue. If you have a support issue, check out the troubleshooting help, and contact information for support, below.

---

Hi everyone - 

I'm sorry to hear that you are having trouble getting the delegated authentication working on PhoneGap. For some background, I'm the engineer that implemented most of this authentication flow in our web client library, so can speak to the various challenges and problems that you might be encountering.

For everyone on this thread, and others who may find it, a few notes:

***Background:***
  - The PhoneGap browser, by default, has no support for popups `window.open(...)`.
  - Invoking `window.open(...)` will, by default, redirect the entire app to the target page.
  - The [InAppBrowser](http://plugins.cordova.io/#/package/org.apache.cordova.inappbrowser) plug-in is responsible for overriding the default `window.open(...)` for pop-ups.

***Firebase Simple Login:***
  - Firebase *Simple Login* refers to Firebase's *deprecated* delegated authentication service. Its client libraries are deprecated and no longer supported, but all of their features have been re-written and are fully-supported in the core Firebase client libraries.
  - For PhoneGap / Cordova, you should be using `firebase.js` at a version `v2.0.0` or later. See [the changelog](https://www.firebase.com/docs/web/changelog.html) for more information.

***Firebase.js Client Logic:***
  - As far as I am aware, there is no existing 'feature detection' API for PhoneGap / Cordova.
  - Whether or not to invoke the custom `InAppBrowser` transport is governed by this expression:

```javascript
return !!(window['cordova'] || window['phonegap'] || window['PhoneGap']) &&
       /ios|iphone|ipod|ipad|android|blackberry|iemobile/i.test(navigator['userAgent']);
```
  - This means that you need (a) `cordova.js` in scope on the page where you are attempting to authenticate, and (b) the *InAppBrowser* enabled for the application.

***Debugging:***
  - On the page where you invoke `ref.authWithOAuthPopup(...)`, try `console.log(cordova)`. Is `cordova` in scope, or undefined? If undefined, look into your build process, or your script includes.
  - Next, on the same page, try `window.open('https://www.google.com', '_blank');`. Is the app loading in the *InAppBrowser*, where you can see the popup frame with an option to close, or is the entire page being redirected? If the latter, dig into why the *InAppBrowser* is not available, starting with the existence of the `cordova` var in the page.
  - If you've verified that the *InAppBrowser* is working properly, now validate that your OAuth application is properly configured by testing OAuth authentication with the provider of your choice on the web.

***Support:***
  - Frustrated, and out of options? Contact me directly at `support@firebase.com` with an "Attn: Rob DiMarco / Cordova" and I'll personally help you debug. If you decide to reach out to support, please include the following:
    - `firebase.js` version
    - PhoneGap / Cordova version
    - A screenshot of your app at the blank-screen, if applicable
    - Which OAuth provider you're using to authenticate
    - If the app is publicly accessible, a resource where we could see a live repro
    - The name of your Firebase

Thanks everyone, I appreciate your patience. I'll do my best to get this resolved for each of you, and ideally we could implement better logic or debugging in the client to make it easier for others in the future.

**Comment by Martin888** [comment]
I had the blank screen after logging in via Facebook.

Installing the inappbrowser [http://plugins.cordova.io/#/package/org.apache.cordova.inappbrowser] sorted me out - just run this in command line: 
**cordova plugin add org.apache.cordova.inappbrowser**

Using $authWithOAuthPopup() in controller code, it now redirects be back to my app in my iOS emulator.

Hope this helps.
M.
